"""
Built-in function implementations for Minimatic.

Provides native implementations of core Wolfram Language functions
including arithmetic, list manipulation, and system functions.
"""

from .arithmetic import (
    Abs,
    Divide,
    Exp,
    Log,
    Minus,
    Plus,
    Power,
    Product,
    Sqrt,
    Subtract,
    Sum,
    Times,
)
from .control import (
    AtomQ,
    Block,
    CompoundExpression,
    Do,
    Evaluate,
    For,
    Fold,
    HeadQ,
    Hold,
    HoldForm,
    If,
    IntegerQ,
    ListQ,
    Map,
    Module,
    Nest,
    NestList,
    NumericQ,
    RealQ,
    ReleaseHold,
    SameQ,
    Set,
    SetDelayed,
    StringQ,
    Switch,
    Table,
    TrueQ,
    UnsameQ,
    Which,
    While,
    With,
)
from .registry import (
    BuiltinFunction,
    BuiltinRegistry,
    builtin_attributes,
    clear_registry,
    get_builtin,
    has_builtin,
    register_builtin,
)
from .io import Request

__all__ = [
    # Registry
    "register_builtin",
    "get_builtin",
    "has_builtin",
    "builtin_attributes",
    "BuiltinFunction",
    "BuiltinRegistry",
    "clear_registry",
    # Arithmetic (exported for direct access)
    "Plus",
    "Times",
    "Power",
    "Minus",
    "Divide",
    "Subtract",
    "Abs",
    "Sqrt",
    "Exp",
    "Log",
    "Sum",
    "Product",
    # Control flow
    "If",
    "Which",
    "Switch",
    "CompoundExpression",
    "Evaluate",
    "ReleaseHold",
    "Hold",
    "HoldForm",
    "Do",
    "While",
    "For",
    "Table",
    "Nest",
    "NestList",
    "Fold",
    "Map",
    "Module",
    "Block",
    "With",
    "Set",
    "SetDelayed",
    "TrueQ",
    "SameQ",
    "UnsameQ",
    "NumericQ",
    "AtomQ",
    "HeadQ",
    "ListQ",
    "StringQ",
    "IntegerQ",
    "RealQ",
    # Web
    "Request",
]
